### ISSUE TITLE
404 page not working in dev mode

### ISSUE THREAD

**Issue by luukbrauckmann** [voorhoede/head-start#135]
The 404 page is not working. If you move the files to `/src/pages` instead of `/src/pages/[locale]` it will work, but you lose the locale parameter so there may be a other way to solve this.

**Comment by luukbrauckmann** [comment]
This is only in development. The 404s do work in production. I researched if there were other ways to redirect the 404s like you can do with Netlify for example, but Cloudflare doesn't provide that possibility at the moment.

**Comment by jbmoelker** [comment]
I wouldn't label this as a bug, but rather a request for improvement of the local development experience.

@decrek do you think we can tweak the current way the 404 dist pages are created, and add a 404 or in the src root that reuses the localised 404 page, like we did temporarily in this workaround? https://github.com/voorhoede/head-start/blob/3b21847c6ffc17412e2414c16374451e641601e9/src/pages/%5Blocale%5D/%5B...path%5D/index.astro#L5

I do think that could lead to less confusion. Otherwise I would label this one as wontfix and close it.
